# Generated by Django 5.0.7 on 2024-10-17 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facultyapp', '0011_marks_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marks',
            name='user',
        ),
    ]
